# Generated by Django 3.1.7 on 2021-03-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passkey', models.CharField(max_length=200)),
                ('encrytext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImgData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgpasskey', models.CharField(max_length=200)),
                ('encryptimg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
