# Generated by Django 2.0.2 on 2021-03-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='AllData',
        ),
    ]
