# Generated by Django 2.0.2 on 2021-03-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210329_1254'),
        ('home', '0002_auto_20210329_1310'),
    ]

    operations = [
    ]
